language: node_js
node_js:
- '4.1'
deploy:
  provider: heroku
  api_key:
    secure: sYyekVLw0m6K0qI0Be3x3Xcq9HEdDwOtlaZ/cPIck1iXupub91gnnFSNqmlg4Pjl0wWe/X2xxIDgxjSOOMKED9iGBkPZ57HRNFWYTKNSwGdcWQcotJ3aAJjc1bQDBtWpjrvPMAeZtUZckVjAXA6RuJhTl65RRKOB+8Uc1dWGC8LmuAQBTi7XgolHgjJ0XYtIIu8goiHZTWxelAw9WqQaOFV+oZ+AbTyS4ca078wDOI4iEDYiO087wGGFPaK5ej/08Ds5VsIDLrdWDIz5lckTkS9M4nNabWbjB8/nstBQptE9LFsIHiZWWiOo4jZ2Srau7qtg5LbCCPPzDMuPrAwu2/Xz+wxAQiAgi5acQdf7gjnQ1283tN7vPs3eXGRPmk+izzfMm1bJOFhwHtqSdJ6RtNrSZn6uy+uEn8l/IfKSst4nYIY4gAZUcOUPaAiIUfByF8URzJGC9qAgb0uHs+1chs2/xLNfDdiRBy219P0942u25cnpovSGKIu2MoNx6JjUYgK2kV6CpT2sAvQWWsZ4fjnfs550FU0hLdlANn3TPh0WVh5yY98eLluG/lQdJClGE5Im6UDyO33qIfEvjzJgr+ZfIyRR/LJ52EDsfMslcYX6KmetsM3OrGqDg82LLm2CVkIYrNC05Trg/EU8MvbdcxNhiikx1yBm5CfDcuMKSGo=
